### PR TITLE
Add memcache middleware.

### PR DESCRIPTION
**Pull request by kailuo-qb**

### CODE REVIEW

**Comment by kailuo-qb** [comment]
@vvakame mind taking a look? Thanks.

**Comment by kailuo-qb** [comment]
@vvakame thank you for the feedbacks, let me work on them and get back to you

**Comment by kailuo-qb** [comment]
@vvakame question: I don't see a `defaultExpiration` in the `aememcache` package.

**Comment by vvakame** [comment]
@kailuo-qb Yes. https://godoc.org/google.golang.org/appengine/memcache#Item
by default. `Expiration` should be zero value of `time.Duration`. It's means `the Item has no expiration time.`.
It's same as https://godoc.org/github.com/bradfitz/gomemcache/memcache#Item .

**Comment by kailuo-qb** [comment]
@vvakame mind taking another look? Thanks.

**Comment by vvakame** [comment]
merged! thank you

**Comment by kailuo-qb** [comment]
@vvakame thank you so much!

**Pull request merged**
